openapi: 3.0.0
info:
  title: E-Commerce Mock API
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /users:
    get:
      summary: Lấy danh sách user (mock)
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              example:
                - id: 1
                  name: "Alice"
                  email: "alice@example.com"
                - id: 2
                  name: "Bob"
                  email: "bob@example.com"

  /categories:
    get:
      summary: Lấy danh sách category (mock)
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              example:
                - id: 1
                  name: "Electronics"
                - id: 2
                  name: "Books"

  /products:
    get:
      summary: Lấy danh sách product (mock)
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              example:
                - id: 101
                  name: "iPhone 15"
                  price: 1200
                  categoryId: 1
                - id: 102
                  name: "MacBook Pro"
                  price: 2500
                  categoryId: 1
                - id: 201
                  name: "Clean Code"
                  price: 30
                  categoryId: 2

  /cart:
    get:
      summary: Lấy giỏ hàng của user (mock)
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              example:
                userId: 1
                items:
                  - productId: 101
                    quantity: 2
                  - productId: 201
                    quantity: 1

  /orders:
    get:
      summary: Lấy danh sách order (mock)
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              example:
                - id: 5001
                  userId: 1
                  status: "PENDING"
                  total: 2430
                - id: 5002
                  userId: 2
                  status: "COMPLETED"
                  total: 30

  /orders/{orderId}/items:
    get:
      summary: Lấy chi tiết order item (mock)
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              example:
                orderId: 5001
                items:
                  - productId: 101
                    quantity: 2
                    price: 1200
                  - productId: 201
                    quantity: 1
                    price: 30
